version: "3.8"

services:
  web:
    container_name: nogan_web_app
    build: ./flask
    ports:
      - 5000:5000

  nginx:
    container_name: nginx_server
    build: ./nginx
    restart: always
    ports:
      - 80:80